config/routes.rb
KairoscopeSys::Application.routes.draw do
  
  resources :contact_messages, :path => 'contato/mensagens'

  resources :projects, :path => :projetos

  get 'credentials' => 'site_pages#credentials'
  get 'admin' => 'site_pages#admin'
  get 'sobre' => 'site_pages#sobre'
  get 'sobre/editar' => 'site_pages#edit_sobre'
  get 'contato' => 'contact_messages#new'
  get 'contato/editar' => 'site_pages#edit_contato'
  resources :site_pages

  devise_for :users, :controllers => { :registrations => "registrations" }
  get 'posts/list' => 'posts#list'
  
  resources :posts, :path => :blog
  
  

  
  root :to => "site_pages#index"
end

app/models/contact_message.rb
class ContactMessage < ActiveRecord::Base
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < ApplicationController
  before_action :set_contact_message, only: [:show, :edit, :update, :destroy]

  # GET /contact_messages
  # GET /contact_messages.json
  def index
    @contact_messages = ContactMessage.all.order(created_at: :asc)
  end

  # GET /contact_messages/1
  # GET /contact_messages/1.json
  def show
  end

  # GET /contact_messages/new
  def new
    @site_page = SitePage.find(2)
    @contact_message = ContactMessage.new
  end

  # GET /contact_messages/1/edit
  def edit
  end

  # POST /contact_messages
  # POST /contact_messages.json
  def create
    @contact_message = ContactMessage.new(contact_message_params)

    respond_to do |format|
      if @contact_message.save
        format.html { redirect_to contato_path, notice: 'Sua mensagem foi enviada com sucesso!' }
        format.json { render action: 'show', status: :created, location: @contact_message }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_messages/1
  # PATCH/PUT /contact_messages/1.json
  def update
    respond_to do |format|
      if @contact_message.update(contact_message_params)
        format.html { redirect_to @contact_message, notice: 'Contact message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_messages/1
  # DELETE /contact_messages/1.json
  def destroy
    @contact_message.destroy
    respond_to do |format|
      format.html { redirect_to contact_messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_message
      @contact_message = ContactMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_message_params
      params.require(:contact_message).permit(:email, :message)
    end
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/views/contact_messages/_form.html.erb
<%= simple_form_for @contact_message, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="form-group xlarge">
	  <%= f.input :email, label: "Seu email", input_html:{class:'form-control span12'} %>
  </div>
  <div class="form-group xlarge">
  	<%= f.input :message, label: "Mensagem", input_html:{class:'form-control span12', rows: '10'} %>
  </div>
  <div class="centered" style="margin-top: 20px;">
    <%= f.button :submit, "Enviar", :class => 'btn-success' %>
  </div>

<% end %>

app/views/contact_messages/edit.html.erb
<%- model_class = ContactMessage -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contact_messages/index.html.erb
<%- model_class = ContactMessage -%>
<div class="page-header">
  <h2>Mensagens Recebidas</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th>Created</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contact_messages.each do |contact_message| %>
      <tr>
        <td><%= contact_message.email %></td>
        <td><%= contact_message.message %></td>
        <td><%= time_ago_in_words(contact_message.created_at)  %> ago</td>
        <td>
          <%= link_to "Ler", contact_message_path(contact_message), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contact_message_path(contact_message),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contact_messages/new.html.erb
<div class="page-header centered">
  <h1>Contato</h1>
</div>

<div class="span6 offset3 gray-box" style="margin-bottom: 150px;">
<%- model_class = ContactMessage -%>

<p><%= @site_page.content.html_safe %></p>
<%= render :partial => 'form' %>
</div>

app/views/contact_messages/show.html.erb
<%- model_class = ContactMessage -%>
<div class="page-header">
  <h3 style="margin-bottom: 0px;">Mensagem de: <%= @contact_message.email %><small style="font-size 14px; margin-top: 15px;" class="pull-right"><%= time_ago_in_words(@contact_message.created_at)  %> ago</small></h3>
</div>


<p><%= @contact_message.message %></p>

<div class="centered last-item" style="margin-top: 25px;">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              contact_messages_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              contact_message_path(@contact_message),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>