config/routes.rb
KairoscopeSys::Application.routes.draw do
  
  resources :contact_messages, :path => 'contato/mensagens'

  resources :projects, :path => :projetos

  get 'credentials' => 'site_pages#credentials'
  get 'admin' => 'site_pages#admin'
  get 'sobre' => 'site_pages#sobre'
  get 'sobre/editar' => 'site_pages#edit_sobre'
  get 'contato' => 'contact_messages#new'
  get 'contato/editar' => 'site_pages#edit_contato'
  resources :site_pages

  devise_for :users, :controllers => { :registrations => "registrations" }
  get 'posts/list' => 'posts#list'
  
  resources :posts, :path => :blog
  
  

  
  root :to => "site_pages#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  def should_generate_new_friendly_id?
    new_record?
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :content, :slug, :visibility, :sidebar, :thumbnail_url)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
	<% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
	
	<div class="row-fluid">
		
		<div class="form-group span9">
			
				<%= f.input :content, :label => false, input_html:{class:'summernote span12'} %>
		
		</div>
		
		<div class="form-group span3 bg-grey">
			<div class="form-group ">
			    <%= f.input :name, input_html:{class:'form-control '} %>
			</div>

			<div class="form-group ">
			    <%= f.input :slug, input_html:{class:'form-control '} %>
			</div>
		    <div class="form-group">
		      <%= f.input :thumbnail_url, input_html: { class: 'input' } %>
		    </div>
			<div class="form-group">
			    <%= f.input :description, input_html:{class:'form-control input-text', rows: '3'} %>
			</div>
		    <div class="form-group">
		      <%= f.input :visibility, collection: ["public", "private"], class:'btn btn-success', selected:  f.object.visibility || 'public', input_html: { class: 'input' } %>
		    </div>
		    <div class="form-group">
		      <%= f.input :sidebar, input_html: { class: 'input-text', rows: '18' } %>
		    </div>
		</div>
		
	</div>
	
	<div class="row-fluid" style="margin-top: 20px;">
    	<div style="text-align: center;">
		  <%= link_to 'voltar', admin_path, class: 'btn' %>
      	  <%= f.button :submit, class:'btn btn-success' %>
		</div>
    </div>
	

	
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.content %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% if @project.sidebar != nil %>
	<div class="span9"><%= @project.content.html_safe %></div>
<% else %>
	<div class="span12"><%= @project.content.html_safe %></div>
<% end %>

<% if @project.sidebar != nil %>
	<div class="span3" >
	<div data-spy="affix" data-offset-top="0" data-offset-right="0" class="gray-box" style="max-width: 203px; margin-right: 20px;">
		<div class="thumbnail" style="margin-bottom: 15px;">
			<img src="<%= @project.thumbnail_url %>">
		</div>
		<div>
			<%= @project.sidebar.html_safe %>
		</div>
	</div>
</div>
<% end %>