config/routes.rb
KairoscopeSys::Application.routes.draw do
  
  resources :contact_messages, :path => 'contato/mensagens'

  resources :projects, :path => :projetos

  get 'credentials' => 'site_pages#credentials'
  get 'admin' => 'site_pages#admin'
  get 'sobre' => 'site_pages#sobre'
  get 'sobre/editar' => 'site_pages#edit_sobre'
  get 'contato' => 'contact_messages#new'
  get 'contato/editar' => 'site_pages#edit_contato'
  resources :site_pages

  devise_for :users, :controllers => { :registrations => "registrations" }
  get 'posts/list' => 'posts#list'
  
  resources :posts, :path => :blog
  
  

  
  root :to => "site_pages#index"
end

app/models/site_page.rb
class SitePage < ActiveRecord::Base
end

app/controllers/site_pages_controller.rb
class SitePagesController < ApplicationController
  before_action :set_site_page, only: [:show, :edit, :update, :destroy]
  before_filter :admin_user, except: [:index, :sobre, :contato, :credentials]

  # GET /site_pages
  # GET /site_pages.json
  def index
    @site_pages = SitePage.order(created_at: :asc).all
    @posts = Post.all.order(created_at: :desc)
  end
  
  def admin
    @site_pages = SitePage.order(created_at: :asc).all
    @posts = Post.all.order(created_at: :desc)
    @projects = Project.all.order(created_at: :desc)
  end

  # GET /site_pages/1
  # GET /site_pages/1.json
  def show
  end

  def sobre
    @site_page = SitePage.find(1)
    @users = User.order(created_at: :asc).find_all_by_team_member("true")
  end
  
  def edit_sobre
    @site_page = SitePage.find(1)
    render action: 'edit'
  end
  
  def contato
    @site_page = SitePage.find(2)
    render action: 'show'
  end
  
  def edit_contato
    @site_page = SitePage.find(2)
    render action: 'edit'
  end
  
  def credentials
  end

  # GET /site_pages/new
  def new
    @site_page = SitePage.new
  end

  # GET /site_pages/1/edit
  def edit
  end

  # POST /site_pages
  # POST /site_pages.json
  def create
    @site_page = SitePage.new(site_page_params)

    respond_to do |format|
      if @site_page.save
        format.html { redirect_to admin_path, notice: 'Variable was successfully created.' }
        format.json { render action: 'admin', status: :created, location: @site_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @site_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_pages/1
  # PATCH/PUT /site_pages/1.json
  def update
    respond_to do |format|
      if @site_page.update(site_page_params)
        format.html { redirect_to admin_path, notice: 'Variable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_pages/1
  # DELETE /site_pages/1.json
  def destroy
    @site_page.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'Variable was deleted.'  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_page
      @site_page = SitePage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_page_params
      params.require(:site_page).permit(:title, :content)
    end
end

app/helpers/site_pages_helper.rb
module SitePagesHelper
end

app/views/site_pages/_form.html.erb
<%= form_for(@site_page) do |f| %>
  <% if @site_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_page.errors.count, "error") %> prohibited this site_page from being saved:</h2>

      <ul>
      <% @site_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_pages/admin.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h3>
	  <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
	  <%= link_to "Novo Post",
	              new_post_path,
	              :class => 'btn btn-primary btn-mini' %>
  </h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="span4"><%= model_class.human_attribute_name(:title) %></th>
      <th class="span6"><%= model_class.human_attribute_name(:description) %></th>
      <th class="span2"><%= model_class.human_attribute_name(:created_at) %></th>
      <th class="span2"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post) %></td>
        <td><%= post.description %></td>
        <td><%= time_ago_in_words( post.created_at) %></td>
        <td>
          <%= link_to "Editar",
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to "Deletar",
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%- model_class = Project -%>
<div class="page-header">
  <h3>
	  <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>
	  <%= link_to "Novo Projeto",
	              new_project_path,
	              :class => 'btn btn-primary btn-mini' %>
  </h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="span4"><%= model_class.human_attribute_name(:name) %></th>
      <th class="span6"><%= model_class.human_attribute_name(:description) %></th>
      <th class="span2"><%= model_class.human_attribute_name(:created_at) %></th>
      <th class="span2"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= truncate( project.description, :length => 60, :omission => '...') %></td>
        <td><%= time_ago_in_words( project.created_at) %></td>
        <td>
          <%= link_to "Editar",
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to "Deletar",
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%- model_class = SitePage -%>
<div class="page-header" style="margin-top: 45px;">
  <h3>Configurações <%= link_to 'Nova Váriavel', new_site_page_path, :class => 'btn btn-mini btn-primary' %></h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
	  <th class="span1"><%= model_class.human_attribute_name(:id) %></th>
      <th class="span4"><%= model_class.human_attribute_name(:title) %></th>
      <th class="span7"><%= model_class.human_attribute_name(:content) %></th>
      <th class="span2"><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @site_pages.each do |site_page| %>
      <tr>
		<td><%= site_page.id %></td>
        <td><%= truncate( site_page.title, :length => 40, :omission => '...') %></td>
        <td><%= truncate( site_page.content, :length => 75, :omission => '...')  %></td>
        <td>
          <%= link_to 'Editar',
                      edit_site_page_path(site_page), :class => 'btn btn-mini' %>
          <%= link_to 'Deletar',
                      site_page_path(site_page),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/site_pages/credentials.html.erb
<div class="alert alert-block alert-error">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4>Página Restrita</h4>
  Você não tem acesso a está página.
</div>

app/views/site_pages/edit.html.erb
<h1>Editing site_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_page %> |
<%= link_to 'Back', site_pages_path %>

app/views/site_pages/index.html.erb
<%- model_class = SitePage -%>

		
		    <div class="thumbnail">
				<% feature_image = @site_pages[2].content %>
				<a href="<%= @site_pages[4].content %>">
					<%= image_tag(feature_image) %>
				</a>

			  <div class="thumbnail-content">
		      	<p><%= @site_pages[3].content %></p>
			  </div>
		    </div>
		</div>
	</div>


<div class="row-fuild">
	<div class="page-header" style="text-align: center; margin-top: 35px; padding-bottom: 0px;">
		 <h2 style="margin-bottom: 5px;">Últimos Posts</h1>
	</div>
</div>


	<% counter = 0 %>
	<ul class="thumbnails" style="margin-left: 0px;">
		<div class="row-fluid">
		<% @posts.each do |post| %>
			<% if counter < 3 %>
				<li class="span4">
				    <div class="thumbnail">
						<%= link_to image_tag(post.cover_image_url), url_for(post) %>
      
					  <div class="thumbnail-content">
				      	<h3><%= link_to post.title, post_path(post) %></h3>
				      	<p><%= post.description %></p>
					  </div>
				    </div>
				</li>
				<% counter = counter + 1 %>
			<% end %>
		<% end %>
	</ul>

app/views/site_pages/new.html.erb
<h1>New site_page</h1>

<%= render 'form' %>

<%= link_to 'Back', site_pages_path %>

app/views/site_pages/show.html.erb
<div style="margin-top: 15px; margin-bottom: 25px;">
<%= @site_page.content.html_safe %>
</div>

app/views/site_pages/sobre.html.erb
<div class="page-header" style="text-align: center; margin-top: 30px; padding-bottom: 5px;">
	 <h2>Sobre</h2>
</div>

<div style="margin-top: 15px; margin-bottom: 25px;">
<%= @site_page.content.html_safe %>
</div>

<% if @users != nil %>
	<div class="page-header" style="text-align: center; margin-top: 30px; padding-bottom: 5px;">
		 <h2 >Equipe</h2>
	</div>


	<% counter = 0 %>
	<ul class="thumbnails">
		<div class="row-fluid" style="margin-bottom: 10px;">
		<% @users.each do |user| %>
			<% if user.first_name && user.last_name && user.description && user.avatar %>
				<% if counter > 3 %>
					</div>
					<div class="row-fluid">
					<% counter = 0 %>
				<% end %>
				<li class="span3">
				    <div class="thumbnail">
						<%= image_tag(user.avatar) %>
	      
					  <div class="thumbnail-content">
				      	<h3><%= user.first_name %> <%= user.last_name %></h3>
						<p><%= user.member_title %></p>
				      	<p><%= user.description %></p>
					  </div>
				    </div>
				</li>
				<% counter = counter + 1 %>
			<% end %>
		<% end %>
	</ul>
<% end %>