config/routes.rb
KairoscopeSys::Application.routes.draw do
  
  resources :contact_messages, :path => 'contato/mensagens'

  resources :projects, :path => :projetos

  get 'credentials' => 'site_pages#credentials'
  get 'admin' => 'site_pages#admin'
  get 'sobre' => 'site_pages#sobre'
  get 'sobre/editar' => 'site_pages#edit_sobre'
  get 'contato' => 'contact_messages#new'
  get 'contato/editar' => 'site_pages#edit_contato'
  resources :site_pages

  devise_for :users, :controllers => { :registrations => "registrations" }
  get 'posts/list' => 'posts#list'
  
  resources :posts, :path => :blog
  
  

  
  root :to => "site_pages#index"
end

app/views/layouts/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-49718700-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "KairoscopeSys" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
	
	<style>
		@font-face {
		    font-family: Futura;
		    src: url("assets/fonts/FuturaStd-Book.otf");
		}
	</style>
	
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
		  <%= link_to image_tag(('kairoscope_logo_web.png'), :style => "margin-left: 2px; margin-top: -2px; position: absolute; width: 200px"), 
		              root_path, :class => "brand", :style => "width: 200px;" %>
          <div class="container-fluid nav-collapse" style="margin-top: 10px;">
            <ul class="nav">
			  <% if @project_list.count > 0%>
				  <li class="dropdown">
				  	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Projetos <b class="caret"></b></a>
				  	<ul class="dropdown-menu">
						<% @project_list.each do |project| %>
	              	  		<li><%= link_to project.name, project_path(project), :class => "menu" %></li>
						<% end %>
				  	</ul>
				  </li>
			  <% end %>
			  <li><%= link_to "Blog", posts_path  %></li>
			  <li><%= link_to "Sobre", sobre_path  %></li>
			  <li><%= link_to "Contato", contato_path  %></li>
            </ul>
			<ul class="nav pull-right">
				<% if user_signed_in? %>
					<%= render 'layouts/page_edit_btn' %>
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<% if current_user.first_name && current_user.last_name %>
							<%= current_user.first_name %> <%= current_user.last_name %> <b class="caret"></b>
						<% else %>
							<%= current_user.email %> <b class="caret"></b>
						<% end %>
					</a>
				    	<ul class="dropdown-menu">
				  			<li><%= link_to 'Edit profile', edit_user_registration_path %></li>
							<% if current_user.try(:admin?) %>
								<li><%= link_to 'Admin', admin_path %></li>
								<li><%= link_to 'Mensagens', contact_messages_path %>
							<% end %>
				  			<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
				<% else %>
				  <li><%= link_to "Sign up", new_user_registration_path %></li>
				  <li><%= link_to "Login", new_user_session_path %></li>
				<% end %>
			</ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Kairoscope 2014</p>
      </footer>

    </div> <!-- /container -->
	
	<%= render 'layouts/analytics' %>


  </body>
</html>